RestAPI/website/music/urls.py
from django.conf.urls import url
from . import views


app_name = 'music'

urlpatterns = [

    # /music/
    url(r'^', views.IndexView.as_view(), name='index'),

    url(r'^register/', views.UserFormView.as_view(), name='register'),

    # /music/music_id/
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),

    # /music/<album_id>/favourite/
    # url(r'^(?P<album_id>[0-9]+)/favourite/$', views.favourite, name='favourite'),

    # music/add/
    url(r'^add/$', views.AlbumCreate.as_view(), name='album-add'),

    # music/update(using key)/
    url(r'^(?P<pk>[0-9]+)/$', views.AlbumUpdate.as_view(), name='album-update'),

    # music/update/delete(using key)/
    url(r'^(?P<pk>[0-9]+)/delete$', views.AlbumDelte.as_view(), name='album-delete')
]

RestAPI/website/website/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url
from django.conf import settings
from django.conf.urls.static import static
from rest_framework.urlpatterns import format_suffix_patterns
#from companies import views

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^', include('music.urls')),
    #url(r'^stocks/', views.StockList.as_view()),
]
#
# urlpatterns = format_suffix_patterns(urlpatterns)
#
#
# if settings.DEBUG:
#     urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_URL)
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_URL)

RestAPI/website/music/models.py
from django.db import models
from django.urls import reverse


class Album(models.Model):
    artist = models.CharField(max_length=250)
    album_title = models.CharField(max_length=500)
    genre = models.CharField(max_length=100)
    album_logo = models.FileField(blank=True,null=True)

    def get_absolute_url(self):
        return reverse('music:detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.artist + " - " + self.album_title


class Song(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    file_type = models.CharField(max_length=10)
    song_title = models.CharField(max_length=250)
    is_favourite = models.BooleanField(default=False)

    def __str__(self):
        return self.song_title + " - " + self.album.artist

RestAPI/website/music/forms.py
from django.contrib.auth.models import User
from django import forms


class Userforms(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password']

RestAPI/website/music/views.py
from django.http import Http404
from django.shortcuts import render, get_object_or_404
from django.template import loader
from .models import Album, Song
#
#
# def index(request):
#     all_albums = Album.objects.all()
#     template = loader.get_template('music/index.html')
#     context = {
#         'all_albums': all_albums,
#     }
#     return render(request, 'music/index.html', context)
#     # return HttpResponse(template.render(context, request))
#
#
# def details(request, album_id):
#     # return HttpResponse("<h2> This is Music Album no. : " + str(album_id) + "</h2>")
#     # albums = Album.objects.get(pk=album_id)
#     albums = get_object_or_404(Album, pk=album_id)
#     return render(request, 'music/detail.html', {'albums': albums})
#
#
# def favourite(request, album_id):
#     albums = get_object_or_404(Album, pk=album_id)
#     try:
#         selected_song = albums.song_set.get(pk=request.POST['song'])
#     except (KeyError, Song.DoesNotExist):
#         return render(request, 'music/detail.html', {
#             'albums': albums,
#             'error_message': "You did not select a valid song"
#         })
#     else:
#         selected_song.is_favourite = True
#         selected_song.save()
#         return render(request, 'music/detail.html', {'albums': albums})


from django.views import generic
from .models import Album, Song
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from django.views.generic import View
from .forms import Userforms


class IndexView(generic.ListView):
    template_name = 'music/index.html'

    def get_queryset(self):
        return Album.objects.all()


class DetailView(generic.DetailView):
    model = Album
    template_name = 'music/detail.html'


class AlbumCreate(CreateView):
    model = Album
    fields = ['artist', 'album_title', 'genre', 'album_logo']


class AlbumUpdate(UpdateView):
    model = Album
    fields = ['artist', 'album_title', 'genre', 'album_logo']


class AlbumDelte(DeleteView):
    model = Album
    success_url = reverse_lazy('music:index')


class UserFormView(View):
    form_class = Userforms
    template_name = 'music/registeration_form.html'

    # display form
    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form': form})

    # post data
    def post(self, request):
        form = self.form_class(request.POST)

        if form.is_valid():
            user = form.save(commit=False)
            # cleaned(normalized) data
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user.set_password(password)
            user.set_username(username)
            user.save()

            # returns User objects if credential are correct
            user = authenticate(username=username, password=password)
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return redirect('music:index')

        return render(request, self.template_name, {'form': form})

RestAPI/website/music/templates/music/album_form.html
{% extends 'music/base.html' %}
{% block title %}Add a New Album{% endblock %}
{% block albums_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                    <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'music/form-template.html' %}
                        <div class="form-group">
                        <div class="col-sm-offset-2 col-sm-10">
                            <button type="submit" class="btn btn-success">Submit</button>

                        </div>
                        </div>
                    </form>

                </div>

            </div>

        </div>
    </div>

</div>
{% endblock %}

RestAPI/website/music/templates/music/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}MUSIC{% endblock %}</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <!--<link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>-->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}"/>

    <style>
    body{
        background-image: url("http://globalmedicalco.com/photos/globalmedicalco/17/81651.jpg");
    }

    .navbar{
        border-radius : 0;
    }

    .navbar-brand{
        font-family : 'Satisfy', cursive;
    }



    </style>

</head>
<body>

<nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'music:index' %}">My Music </a>
        </div>

        <!--Items-->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="active">
                    <a href="{% url 'music:index' %}">
                        <span class="glyphicon glyphicon-cd" aria-hidden="true"></span>&nbsp; Albums
                    </a>
                </li>

                <li class="">
                    <a href="#">
                        <span class="glyphicon glyphicon-music" aria-hidden="true"></span>&nbsp; Songs
                    </a>
                </li>
            </ul>


            <form class="navbar-form navbar-left" role="search" method="get" action="#">
                <div class="form-group">
                    <input type="text" class="form-control" name="q" value="">
                </div>
                <button type="submit" class="btn btn-default">Search</button>
            </form>

            <ul class=" nav navbar-nav navbar-right">
                #Add Albums
                <li class="">
                    <a href="{% url 'music:album-add' %}">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Add Albums
                    </a>
                </li>
                # Log Out
                <li class="">
                    <a href="#">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Log Out
                    </a>
                </li>
            </ul>
        </div>

    </div>
</nav>
{% block body %}
{% endblock %}

</body>
</html>

RestAPI/website/music/templates/music/detail.html
{% extends 'music/base.html' %}
{% block title %}Album Details{% endblock %}
{% block body %}

<h1>{{ album.album_title }}</h1>
<h3>{{ album.artist }}</h3>
{% if error_message %}
<p><strong>{{ error_message }}</strong></p>
{% endif %}

{% for song in album.song_set.all %}
    {{ song.song_title }}
    {% if song.is_favourite %}
        <img src="http://i.imgur.com/b9b13Rd.png"/>
    {% endif %}
    <br>
{% endfor %}
{% endblock %}

RestAPI/website/music/templates/music/form-template.html
{% for field in form %}
<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <span class="text-danger small">{{ field.errors }}</span>
    </div>
    <label class="control-label col-sm-2">{{ field.label_tag }}</label>
    <div class="col-sm-10">{{ field }}</div>
</div>
{% endfor %}

RestAPI/website/music/templates/music/index.html
{% extends 'music/base.html' %}
{% block body %}
<h2>Here are all my Albums</h2>
{% if object_list %}
<ul>
    {% for albums in object_list %}
    <li>
        <a href="{% url 'music:detail' albums.id %}"> {{ albums.artist }}</a>
    </li>
    {% endfor %}
</ul>
{% else %}
<h3>Please add some albums to your list</h3>
{% endif%}
{% endblock %}

RestAPI/website/music/templates/music/registration_form.html
{% extends 'music/base.html' %}
{% block title %}Register{% endblock %}

{% block body %}
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Create a New Account</h3>
                    <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'music/form-template.html' %}
                        <div class="form-group">
                        <div class="col-sm-offset-2 col-sm-10">
                            <button type="submit" class="btn btn-success">Submit</button>

                        </div>
                        </div>
                    </form>

                </div>

            </div>

        </div>
    </div>

</div>
{% endblock %}